version: '3.2'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - .mysql:/var/lib/mysql
  php:
    image: richarvey/nginx-php-fpm
    depends_on:
      - mysql
    expose:
      - '80'
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
